**INVENTORY AND PROFITABILITY ANALYSIS**

This project analyzes project-level financial performance for a carpentry business using SQLite and Python.

The objective is to:
- Evaluate profitability across projects
- Identify high-margin and low-margin projects
- Detect loss-making projects
- Analyze performance by product type and client

Load Data

In [ ]:
import pandas as pd

df = pd.read_csv('projects.csv')
df.head()

,PROJECT_ID,PROJECT_NAME,CLIENT,PRODUCT_TYPE,QUANTITY,COST_TOTAL,PRICE,PROFIT,MARGIN
0,P001,11 Entrepaños,Client 007,SHELVES,11,3095.0,6949.44,3854.44,0.554640
1,P002,3 Mesa redonda,Client 002,TABLE,3,7770.0,14426.67,6656.67,0.461414
2,P003,Bufetera y repisas,Client 013,FURNITURE,1,10653.0,8750.00,-1903.00,-0.217486
3,P004,Cabecera/closet,Client 014,CLOSET,1,25680.0,55319.00,29639.00,0.535783
4,P005,Cajonera,Client 010,FURNITURE,1,7655.0,23130.00,15475.00,0.669045

Create SQLite Database

In [ ]:
import sqlite3

conn = sqlite3.connect(':memory:')
df.to_sql('projects', conn, index=False, if_exists='replace')

30

Create Analysis View

In [ ]:
query = """
CREATE VIEW project_analysis AS
SELECT
    PROJECT_ID,
    PROJECT_NAME,
    CLIENT,
    PRODUCT_TYPE,
    QUANTITY,
    COST_TOTAL,
    PRICE,
    PROFIT,
    MARGIN
FROM projects;
"""

conn.execute(query)

Most Profitable Projects

In [ ]:
query = """
SELECT PROJECT_NAME, PROFIT
FROM project_analysis
ORDER BY PROFIT DESC;
"""

pd.read_sql(query, conn)

                                       PROJECT_NAME    PROFIT
0                                   Cabecera/closet  29639.00
1                                   Puerta en Nogal  21930.00
2                                          Cajonera  20190.00
3                                          Cajonera  18375.00
4                                  Puerta en Parota  17960.59
5                                  Puerta en Encino  16017.06
6                                    Librero Grande  15850.00
7                                          Cajonera  15475.00
8                           Puerta en Pino Estufado  13830.00
9                                   Closet Completo  11520.50
10                              Closet lado ventana  10237.75
11                                   3 Mesa redonda   6656.67
12                                          Puertas   5248.89
13                                       Escritorio   5010.00
14                                       Mesa Común   3997.67
15                                    11 Entrepaños   3854.44
16                                           Vanity   3423.00
17                                     Linea Normal   3357.26
18                                     Linea normal   3261.84
19                       Pintura puertas y ventanas   3235.56
20  Closet sencillo 140 ancho x 210 alto y 50 fondo   3212.89
21                                   Puertas Cocina   2927.11
22                             Puertas Hueco 50x 81   2002.22
23                                  Mesa de trabajo   1813.89
24                         Restauracion Mueble uñas   1263.33
25                                 Mueble esquinero   1155.56
26                                        Entrepaño    597.22
27                                 Puerta de tambor    208.56
28                                    Linea Cubrica  -1690.79
29                               Bufetera y repisas  -1903.00

### Insight
The results show which projects generate the highest profit, indicating strong pricing strategies and efficient cost management.

Loss-Making Projects

In [ ]:
query = """
SELECT PROJECT_NAME, PROFIT
FROM project_analysis
WHERE PROFIT < 0;
"""

pd.read_sql(query, conn)

         PROJECT_NAME   PROFIT
0  Bufetera y repisas -1903.00
1       Linea Cubrica -1690.79

### Insight
Some projects show negative profit, suggesting pricing or cost inefficiencies that should be reviewed.

Profitability by Product Type

In [ ]:
query = """
SELECT
    PRODUCT_TYPE,
    AVG(MARGIN) AS AVG_MARGIN
FROM project_analysis
GROUP BY PRODUCT_TYPE
ORDER BY AVG_MARGIN DESC;
"""

pd.read_sql(query, conn)

    PRODUCT_TYPE  AVG_MARGIN
0        RENEWAL    0.548364
1        SHELVES    0.526740
2  CABINET DOORS    0.523013
3           DESK    0.521875
4          DOORS    0.494297
5         CLOSET    0.440112
6          TABLE    0.432902
7      FURNITURE    0.396160
8           DOOR    0.384483
9     BOOKSELLER    0.265828

### Insight
Different product types show variability in margins, highlighting which categories are more profitable.

Revenue by Client

In [ ]:
query = """
SELECT
    CLIENT,
    SUM(PRICE) AS TOTAL_REVENUE
FROM project_analysis
GROUP BY CLIENT
ORDER BY TOTAL_REVENUE DESC;
"""

pd.read_sql(query, conn)

        CLIENT  TOTAL_REVENUE
0   Client 001      153077.65
1   Client 002       86358.90
2   Client 014       55319.00
3   Client 016       53322.75
4   Client 013       35640.50
5   Client 007       27168.33
6   Client 012       23738.31
7   Client 015       23130.00
8   Client 010       23130.00
9   Client 009       10906.45
10  Client 011        9263.00
11  Client 003        6748.89
12  Client 004        6422.11
13  Client 008        3837.78
14  Client 005        3392.22
15  Client 006        2613.33

### Insight
This analysis identifies key clients contributing most to revenue.

Conclusion

Load Materials

In [ ]:
materials = pd.read_csv('materials.csv')
materials.head()

,PROJECT_NAME,CLIENT,MATERIAL,QUANTITY,UNIT_COST,TOTAL_COST,CALCULATED_TOTAL,COST_DIFFERENCE,CATEGORY,TYPE,GROUP_NAME,DIMENSIONS,THICKNESS,WIDTH,LENGTH,VOLUME,PRODUCT_TYPE,PROJECT_ID
0,Puerta en Parota,Client 001,TABLA 1X6X8 PAROTA,8.0,720.0,5760.0,5760.0,0.0,TABLAS,BOARD,RAW_MATERIAL,1X6X8,1.0,6.0,8.0,48.0,DOOR,P024
1,Puerta en Parota,Client 001,TABLA 1X8X8 PAROTA,20.0,650.0,13000.0,13000.0,0.0,TABLAS,BOARD,RAW_MATERIAL,1X8X8,1.0,8.0,8.0,64.0,DOOR,P024
2,Puerta en Parota,Client 001,BARNIZ EXTERIOR,2.0,350.0,700.0,700.0,0.0,SOLVENTE,VARNISH,FINISHING,NaN,NaN,NaN,NaN,NaN,DOOR,P024
3,Puerta en Parota,Client 001,FONDO SELLADOR,2.0,300.0,600.0,600.0,0.0,SOLVENTE,SEALER,FINISHING,NaN,NaN,NaN,NaN,NaN,DOOR,P024
4,Puerta en Parota,Client 001,LIJAS,20.0,20.0,400.0,400.0,0.0,LIJAS,SANDPAPER,FINISHING,NaN,NaN,NaN,NaN,NaN,DOOR,P024

In [ ]:
materials.to_sql('materials', conn, index=False, if_exists='replace')

429

Most Expensive Materials

In [ ]:
query = """
SELECT
    MATERIAL,
    SUM(TOTAL_COST) AS TOTAL_COST
FROM materials
GROUP BY MATERIAL
ORDER BY TOTAL_COST DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

                      MATERIAL  TOTAL_COST
0                 TRIPLAY 15MM     31050.0
1                         16MM     23000.0
2  TABLA 1X8X8 NOGAL AMERICANO     22000.0
3                 TRIPLAY 16MM     13400.0
4           TABLA 1X8X8 PAROTA     13000.0
5                        FLETE     12150.0
6           TABLA 1X8X8 ENCINO     11000.0
7                     MDF 16MM      7675.0
8                  TRIPLAY 6MM      7650.0
9                          6MM      7570.0

The analysis identifies the main cost drivers, showing which materials contribute most to total project costs.

Cost distribution by category

In [ ]:
query = """
SELECT
    CATEGORY,
    SUM(TOTAL_COST) AS CATEGORY_COST
FROM materials
GROUP BY CATEGORY
ORDER BY CATEGORY_COST DESC;
"""

pd.read_sql(query, conn)

      CATEGORY  CATEGORY_COST
0       TABLAS        82990.0
1   ENCHAPADOS        72885.0
2   FERRETERIA        62520.0
3     SOLVENTE        33315.0
4         OTRO        18895.0
5          MDF        13925.0
6  TERMINACION        12672.0
7     MELAMINA        11550.0
8        LIJAS         4750.0
9        TINTA         2610.0

In [ ]:
query = """
SELECT
    p.PROJECT_NAME,
    p.PRODUCT_TYPE,
    p.PROFIT,
    SUM(m.TOTAL_COST) AS MATERIAL_COST
FROM projects p
JOIN materials m
ON p.PROJECT_ID = m.PROJECT_ID
GROUP BY p.PROJECT_ID
ORDER BY p.PROFIT DESC;
"""

pd.read_sql(query, conn)

,PROJECT_NAME,PRODUCT_TYPE,PROFIT,MATERIAL_COST
0,Cabecera/closet,CLOSET,29639.00,25680.0
1,Puerta en Nogal,DOOR,21930.00,31710.0
2,Cajonera,FURNITURE,20190.00,15350.0
3,Cajonera,FURNITURE,18375.00,15350.0
4,Puerta en Parota,DOOR,17960.59,22070.0
5,Puerta en Encino,DOOR,16017.06,17350.0
6,Librero Grande,BOOKSELLER,15850.00,43775.0
7,Cajonera,FURNITURE,15475.00,15350.0
8,Puerta en Pino Estufado,DOOR,13830.00,12210.0
9,Closet Completo,CLOSET,11520.50,15370.0
10,Closet lado ventana,CLOSET,10237.75,19955.0
11,3 Mesa redonda,TABLE,6656.67,7770.0
12,Puertas,DOORS,5248.89,5370.0
13,Escritorio,DESK,5010.00,4590.0
14,Mesa Común,TABLE,3997.67,3034.0
15,11 Entrepaños,SHELVES,3854.44,3095.0
16,Vanity,FURNITURE,3423.00,5840.0
17,Linea Normal,FURNITURE,3357.26,5260.0
18,Linea normal,FURNITURE,3261.84,3825.0
19,Pintura puertas y ventanas,RENEWAL,3235.56,2040.0
20,Closet sencillo 140 ancho x 210 alto y 50 fondo,CLOSET,3212.89,3815.0
21,Puertas Cocina,CABINET DOORS,2927.11,3495.0
22,Puertas Hueco 50x 81,CABINET DOORS,2002.22,1390.0
23,Mesa de trabajo,TABLE,1813.89,4935.0
24,Restauracion Mueble uñas,RENEWAL,1263.33,1350.0
25,Mueble esquinero,FURNITURE,1155.56,1485.0
26,Entrepaño,SHELVES,597.22,600.0
27,Puerta de tambor,DOOR,208.56,3670.0
28,Linea Cubrica,FURNITURE,-1690.79,9725.0
29,Bufetera y repisas,FURNITURE,-1903.00,10653.0

In [ ]:
query = """
SELECT
    PROJECT_NAME,
    PRODUCT_TYPE,
    COST_TOTAL / QUANTITY AS COST_PER_UNIT,
    PRICE / QUANTITY AS PRICE_PER_UNIT
FROM projects;
"""

pd.read_sql(query, conn)

,PROJECT_NAME,PRODUCT_TYPE,COST_PER_UNIT,PRICE_PER_UNIT
0,11 Entrepaños,SHELVES,281.363636,631.767273
1,3 Mesa redonda,TABLE,2590.000000,4808.890000
2,Bufetera y repisas,FURNITURE,10653.000000,8750.000000
3,Cabecera/closet,CLOSET,25680.000000,55319.000000
4,Cajonera,FURNITURE,7655.000000,23130.000000
5,Cajonera,FURNITURE,4755.000000,23130.000000
6,Cajonera,FURNITURE,2940.000000,23130.000000
7,Closet Completo,CLOSET,15370.000000,26890.500000
8,Closet lado ventana,CLOSET,19955.000000,30192.750000
9,Closet sencillo 140 ancho x 210 alto y 50 fondo,CLOSET,3815.000000,7027.890000
10,Entrepaño,SHELVES,600.000000,1197.220000
11,Escritorio,DESK,4590.000000,9600.000000
12,Librero Grande,BOOKSELLER,43775.000000,59625.000000
13,Linea Cubrica,FURNITURE,9725.000000,8034.210000
14,Linea Normal,FURNITURE,5260.000000,8617.260000
15,Linea normal,FURNITURE,3825.000000,7086.840000
16,Mesa Común,TABLE,3034.000000,7031.670000
17,Mesa de trabajo,TABLE,4935.000000,6748.890000
18,Mueble esquinero,FURNITURE,1485.000000,2640.560000
19,Pintura puertas y ventanas,RENEWAL,2040.000000,5275.560000
20,Puerta de tambor,DOOR,3670.000000,3878.560000
21,Puerta en Encino,DOOR,17350.000000,33367.060000
22,Puerta en Nogal,DOOR,31710.000000,53640.000000
23,Puerta en Parota,DOOR,22070.000000,40030.590000
24,Puerta en Pino Estufado,DOOR,12210.000000,26040.000000
25,Puertas,DOORS,5370.000000,10618.890000
26,Puertas Cocina,CABINET DOORS,3495.000000,6422.110000
27,Puertas Hueco 50x 81,CABINET DOORS,1390.000000,3392.220000
28,Restauracion Mueble uñas,RENEWAL,1350.000000,2613.330000
29,Vanity,FURNITURE,5840.000000,9263.000000

In [ ]:
query = """
SELECT
    PROJECT_NAME,
    PRODUCT_TYPE,
    COST_TOTAL,
    PRICE,
    PROFIT,
    MARGIN
FROM projects
ORDER BY MARGIN ASC;
"""

pd.read_sql(query, conn)

,PROJECT_NAME,PRODUCT_TYPE,COST_TOTAL,PRICE,PROFIT,MARGIN
0,Bufetera y repisas,FURNITURE,10653.0,8750.00,-1903.00,-0.217486
1,Linea Cubrica,FURNITURE,9725.0,8034.21,-1690.79,-0.210449
2,Puerta de tambor,DOOR,3670.0,3878.56,208.56,0.053773
3,Librero Grande,BOOKSELLER,43775.0,59625.00,15850.00,0.265828
4,Mesa de trabajo,TABLE,4935.0,6748.89,1813.89,0.268769
5,Closet lado ventana,CLOSET,19955.0,30192.75,10237.75,0.339080
6,Vanity,FURNITURE,5840.0,9263.00,3423.00,0.369535
7,Linea Normal,FURNITURE,5260.0,8617.26,3357.26,0.389597
8,Puerta en Nogal,DOOR,31710.0,53640.00,21930.00,0.408837
9,Closet Completo,CLOSET,15370.0,26890.50,11520.50,0.428423
10,Mueble esquinero,FURNITURE,1485.0,2640.56,1155.56,0.437619
11,Puerta en Parota,DOOR,22070.0,40030.59,17960.59,0.448672
12,Puertas Cocina,CABINET DOORS,3495.0,6422.11,2927.11,0.455786
13,Closet sencillo 140 ancho x 210 alto y 50 fondo,CLOSET,3815.0,7027.89,3212.89,0.457163
14,Linea normal,FURNITURE,3825.0,7086.84,3261.84,0.460267
15,3 Mesa redonda,TABLE,7770.0,14426.67,6656.67,0.461414
16,Puerta en Encino,DOOR,17350.0,33367.06,16017.06,0.480026
17,Restauracion Mueble uñas,RENEWAL,1350.0,2613.33,1263.33,0.483418
18,Puertas,DOORS,5370.0,10618.89,5248.89,0.494297
19,Entrepaño,SHELVES,600.0,1197.22,597.22,0.498839
20,Escritorio,DESK,4590.0,9600.00,5010.00,0.521875
21,Puerta en Pino Estufado,DOOR,12210.0,26040.00,13830.00,0.531106
22,Cabecera/closet,CLOSET,25680.0,55319.00,29639.00,0.535783
23,11 Entrepaños,SHELVES,3095.0,6949.44,3854.44,0.554640
24,Mesa Común,TABLE,3034.0,7031.67,3997.67,0.568524
25,Puertas Hueco 50x 81,CABINET DOORS,1390.0,3392.22,2002.22,0.590239
26,Pintura puertas y ventanas,RENEWAL,2040.0,5275.56,3235.56,0.613311
27,Cajonera,FURNITURE,7655.0,23130.00,15475.00,0.669045
28,Cajonera,FURNITURE,4755.0,23130.00,18375.00,0.794423
29,Cajonera,FURNITURE,2940.0,23130.00,20190.00,0.872892

In [ ]:
query = """
SELECT
    p.PRODUCT_TYPE,
    AVG(m.TOTAL_COST) AS AVG_MATERIAL_COST
FROM materials m
JOIN projects p
ON m.PROJECT_ID = p.PROJECT_ID
GROUP BY p.PRODUCT_TYPE;
"""

pd.read_sql(query, conn)

    PRODUCT_TYPE  AVG_MATERIAL_COST
0     BOOKSELLER        2431.944444
1  CABINET DOORS         212.391304
2         CLOSET        1012.812500
3           DESK         327.857143
4           DOOR        1450.166667
5          DOORS         383.571429
6      FURNITURE         490.165680
7        RENEWAL         242.142857
8        SHELVES         263.928571
9          TABLE         403.564103

### Key Findings

- Material costs are concentrated in a small number of high-impact items
- Profitability varies significantly across projects and product types
- Some projects operate with low or negative margins, indicating inefficiencies
- Unit-level analysis reveals differences in pricing strategy
- Material consumption plays a critical role in overall cost structure

### Business Impact

These insights can support:
- Cost reduction strategies
- Pricing optimization
- Focus on high-margin products
- Better resource allocation

### Key Findings

- Profitability varies across projects and product types
- Some projects operate at a loss, indicating inefficiencies
- Certain product categories generate higher margins
- Revenue is concentrated among specific clients

### Business Impact

These insights can support:
- Pricing optimization
- Cost control strategies
- Focus on high-margin products
- Better client targeting